### PR TITLE
Move citations from homepage to separate page

### PR DESCRIPTION
**Pull request by hjstroud**
This PR aims to declutter the homepage by removing the Citation heading (and its contents) from the homepage and moving it to a separate page that appears in the contents sidebar.

One note on this: when we were initially testing this change, the contents sidebar was not updating correctly, and it was necessary to run `make clean` before building the html in order for the heading of the new page to show up in the contents sidebar on all pages.

We plan to include a link to this page within the text on the homepage (e.g. To cite Nanover, see this page), but this may be better achieved in a separate PR once the rest of the text on the homepage has been settled on.

### CODE REVIEW

**Comment by rhoslynroebuck** [comment]
Yeah this looks good to me

**Review by rhoslynroebuck — APPROVED** [review]
Looks good to me

**Review by jbarnoud — APPROVED** [review]
Why not? Will it be obvious enough that there is something that can be cited?

**Comment by jbarnoud** [comment]
Good ideas!

**Pull request merged**
